INSERT INTO athletes (name, statletik_id, gender, birth_year) VALUES
                                                                  ('Oswald', 310611, 'MALE', 2002),
                                                                  ('Chris', 311583, 'MALE', 1997),
                                                                  ('Arthur', 281136, 'MALE', 1999),
                                                                  ('Andreas', 520627, 'MALE', 2005),
                                                                  ('Grønbech', 299118, 'MALE', 2002),
                                                                  ('Malte', 328355, 'MALE', 2003),
                                                                  ('Noah', 310680, 'MALE', 2003),
                                                                  ('Rasmus', 299097, 'MALE', 1999),
                                                                  ('Skovhauge', 311667, 'MALE', 2003),
                                                                  ('Slips', 137378, 'MALE', 1993),
                                                                  ('Sofus', 299144, 'MALE', 2004),
                                                                  ('Suurballe', 310678, 'MALE', 2002),
                                                                  ('Theo', 311665, 'MALE', 2004),
                                                                  ('Victor', 674166, 'MALE', 2001),
                                                                  ('Betty', 222289, 'FEMALE', 2004),
                                                                  ('Brix', 126533, 'FEMALE', 1996),
                                                                  ('Freja', 229186, 'FEMALE', 2005),
                                                                  ('Josephine', 222256, 'FEMALE', 2003),
                                                                  ('Karla', 209751, 'FEMALE', 2003),
                                                                  ('Koch', 149001, 'FEMALE', 1999),
                                                                  ('Nickoline', 141597, 'FEMALE', 1998),
                                                                  ('Thyra', 449176, 'FEMALE', 2003)
    ON CONFLICT (statletik_id) DO NOTHING;